
theme: jekyll-theme-midnight
title: CIT281 Project 5
description: Update and write node.js javascript code to execute a “monster game” which will report random drains to each monster’s health within the console.
